const express = require("express");
const region = express.Router();
const validarCreateRegion = require("../../middlewares/region/validarCreateRegion");
const validarModifyRegion = require("../../middlewares/region/validarModifyRegion");
const validarCreatePais = require("../../middlewares/region/pais/validarCreatePais");
const validarModifyPais = require("../../middlewares/region/pais/validarModifyPais");
const validarDeletePais = require("../../middlewares/region/pais/validarDeletePais");
const validarCreateCiudad = require("../../middlewares/region/ciudad/validarCreateCiudad");
const validarModifyCiudad = require("../../middlewares/region/ciudad/validarModifyCiudad");
const validarDeleteCiudad = require("../../middlewares/region/ciudad/validarDeleteCiudad");
const crearCiudad = require("../../controllers/region/ciudad/crearCiudad");
const modificarCiudad = require("../../controllers/region/ciudad/modificarCiudad");
const eliminarCiudad = require("../../controllers/region/ciudad/eliminarCiudad");
const crearPais = require("../../controllers/region/pais/crearPais");
const modificarPais = require("../../controllers/region/pais/modificarPais");
const eliminarPais = require("../../controllers/region/pais/eliminarPais");
const crearRegion = require("../../controllers/region/crearRegion");
const modificarRegion = require("../../controllers/region/modificarRegion");
const eliminarRegion = require("../../controllers/region/eliminarRegion");
const obtenerRegiones = require("../../controllers/region/obtenerRegiones");
const obtenerNombreRegiones = require("../../controllers/region/obtenerNombreRegiones");
const obtenerNombrePaises = require("../../controllers/region/pais/obtenerNombrePaises");
const obtenerNombreCiudades = require("../../controllers/region/ciudad/obtenerNombreCiudades");

region.post("/paises/nombres", obtenerNombrePaises);
region.post("/ciudades/nombres", obtenerNombreCiudades);
region.post("/ciudades/:id", validarCreateCiudad, crearCiudad);
region.put("/ciudades/:id", validarModifyCiudad, modificarCiudad);
region.delete("/ciudades/:id", validarDeleteCiudad, eliminarCiudad);
region.post("/paises/:id", validarCreatePais, crearPais);
region.put("/paises/:id", validarModifyPais, modificarPais);
region.delete("/paises/:id", validarDeletePais, eliminarPais);
region.put("/:id", validarModifyRegion, modificarRegion);
region.delete("/:id", eliminarRegion);
region.post("/", validarCreateRegion, crearRegion);
region.post("/nombres", obtenerNombreRegiones);
region.get("/", obtenerRegiones);

module.exports = region;
